### ISSUE TITLE
 Is it possible to create dependencies across different org files and set triggers to alter tags ?

### ISSUE THREAD

**Issue by lyndhurst** [toshism/org-linker-edna#17]
Hi,

I am fairly new to Emacs and I am not familiar with Helm unfortunately, I am a Doom Emacs and Consult user.

Your package really looks like the little workflow push my GTD implementation desperately needs, so thank you for that :+1:
I managed to install your packages and the dependencies without any issues.

Most dependencies I would be using `org-linker-edna` for, are between tasks located in different org files, and trying out the command, I am only offered to pick a candidate from the current buffer.  I checked variables, and all I found was `org-linker-buffer-function` which is set to `org-agenda-files`.

I still suck at Elisp, but I tried looking at `org-edna-linker.el`. I feel like I could maybe override the function below so it looks for headers through all my agenda files. Before I waste days trying to make it work, I decided to try and ask you first if there is any chance that could work...

```lisp
(defun org-linker-edna-todo-candidates ()
  (buffer-local-value 'org-todo-keywords-1 (current-buffer)))

```

On top of that the triggers I was thinking of using were almost exclusively about removing tags; and when testing out, I could 'only' mess wiih schedule, deadline and todo. Do you think I could add that too, or would I be better off rethinking my workflow ?

Thanks for your time.

**Comment by novoid** [comment]
I'm not the maintainer but a user of org-linker-edna.

Yes, you can link dependencies across different org files. At least of they are within the list of your agenda files. I don't know if this is a requirements but it's the case with my files and I'd assume so (otherwise it would be hard to determine the link target).

Your question related to adding/removing tags doesn't refer to this project. You should look at https://www.nongnu.org/org-edna-el/ which explains org-edna. "Actions" does list the ability to trigger a tag: https://www.nongnu.org/org-edna-el/#org29a9491

Btw, you can find some blog articles of mine where I write about my personal org-linker-edna workflows on https://duckduckgo.com/?q=edna+site%3AKarl-Voit.at&ia=web Maybe this gives you additional impressions on how to use this.

**Comment by lyndhurst** [comment]
Thanks for your reply. I went for a different solution because I really couldn't get helm to work the way I needed to. For your blog, I had already read it, thanks, that was helpful and lead me to this repo. I guess I forgot to close the issue when I found a workaround. Thanks again 👍
